version: 2
updates:
  - package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    groups:
      all-dependencies:
        patterns:
          - '*'
    directories:
      - '/'
      - '/packages/*'
      - '/docs'
