version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
      - '/docs'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    groups:
      all-dependencies:
        patterns:
          - '*'
    commit-message:
      prefix: 'fix'
      include: 'scope'
