version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    commit-message:
      prefix: 'fix(Dependabot)'

  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: daily
      timezone: 'Asia/Shanghai'
      time: '09:00'
    commit-message:
      prefix: 'fix(Dependabot)'
