version: 2

updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
      - '/docs'
      - '/blog'
    schedule:
      interval: 'daily'
      timezone: 'Asia/Shanghai'
      time: '09:00'
    commit-message:
      prefix: 'fix(Dependabot)'
