name: Publish Any Commit

on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'
    paths:
      - 'packages/Lumen/**'
      - 'packages/Solis/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' &&
      github.event.head_commit != null && 
      startsWith(github.event.head_commit.message, 'release:') == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: corepack enable

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: build
        run: pnpm run package:solis

      - name: Release
        run: pnpm dlx pkg-pr-new publish --compact --pnpm './packages/*'
