name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'Lumen@*'
      - 'Solis@*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - if: startsWith(github.ref, 'refs/tags/Lumen@')
        run: cd packages/Lumen && npx changelogithub --no-group
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - if: startsWith(github.ref, 'refs/tags/Solis@')
        run: cd packages/Solis && npx changelogithub --no-group
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
